language: python
dist: xenial

addons:
  apt:
    packages:
      - openmpi-bin
      - libopenmpi-dev

cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - python: 3.5
      env:
      - TOXENV=py35
    - python: 3.6
      env:
      - TOXENV=py36
    - python: 3.7
      env:
      - TOXENV=py37
    - python: 3.8
      env:
      - TOXENV=py38
    - python: 3.5
      env:
      - TOXENV=py35-mpi
    - python: 3.6
      env:
      - TOXENV=py36-mpi
    - python: 3.7
      env:
      - TOXENV=py37-mpi
    - python: 3.8
      env:
      - TOXENV=py38-mpi
    - python: 3.7
      env:
      - TOXENV=flake8
    - python: 3.7
      env:
      - TOXENV=pylint
    - python: 3.7
      env:
      - TOXENV=docs
    - python: 3.7
      env:
      - TOXENV=check-manifest
    - python: 3.7
      env:
      - TOXENV=checkreadme

before_install:
  - pip install codecov # for coverage

install:
  - pip install tox

script:
  - tox

after_success:
  - codecov
